version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g yarn typescript
      - yarn install
  build:
    commands:
      - yarn
      - yarn build
  post_build:
    commands:
      - echo "Starting the project..."
      - yarn start